# Generated by Django 4.2.3 on 2023-09-20 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0007_alter_post_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='updated',
            new_name='update',
        ),
    ]
